(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const sections=[['inicio','Inicio'],['geografia','Geografía física'],['humana','Geografía humana'],['economia','Economía'],['cultura','Cultura'],['desafios','Desafíos'],['juegos','Juegos'],['recursos','Fuentes'],['explora','Explora']];
function setupNav(){
 const nav=document.createElement('nav');nav.id='proNav';nav.setAttribute('aria-label','Navegación principal');
 sections.forEach(([id,label])=>{const a=document.createElement('a');a.href='#'+id;a.textContent=label;nav.appendChild(a)});document.body.appendChild(nav);
 const links=$$('#proNav a');const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){links.forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}}),{rootMargin:'-25% 0px -65%'});sections.forEach(([id])=>$( '#'+id)&&obs.observe($('#'+id));
 const bar=document.createElement('div');bar.className='pro-progress';bar.innerHTML='<i></i>';document.body.appendChild(bar);const fill=$('.pro-progress i');
 addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;fill.style.width=(h>0?(scrollY/h)*100:0)+'%'},{passive:true});
}
const details={
 ubicacion:{t:'Ubicación y límites',tag:'GEOGRAFÍA FÍSICA',body:'La Región Andina ocupa el sector central de Colombia y se estructura alrededor de la cordillera de los Andes. Su relieve conecta el occidente y el oriente del país mediante valles, altiplanos, laderas y pasos de montaña. Para estudiar sus límites conviene observar la transición hacia las regiones Caribe, Pacífica, Orinoquía, Amazonía y los valles de los grandes ríos.',heads:[['¿Por qué importa?', 'La posición central favorece la conexión entre territorios, pero el relieve también eleva los costos y dificultades de construir infraestructura.'],['Cómo estudiarla','Compara altitud, pendiente, ríos, ciudades y vías: juntos explican buena parte de la organización espacial andina.'],['Clave','La región no es solo “montaña”: incluye valles y altiplanos donde se concentran población y actividades económicas.']]},
 relieve:{t:'Relieve y cordilleras',tag:'GEOGRAFÍA FÍSICA',body:'En Colombia, los Andes se dividen en tres grandes cordilleras: Occidental, Central y Oriental. Entre ellas se forman valles y cuencas que han permitido diferentes formas de poblamiento y producción. La Cordillera Central alberga numerosos volcanes y cumbres de gran altitud; la Oriental incluye extensos altiplanos y sistemas montañosos que condicionan el clima y las comunicaciones.',heads:[['Occidental','Se ubica hacia el occidente del sistema andino y se relaciona con los corredores hacia el Pacífico.'],['Central','Presenta volcanismo, altas cumbres y paisajes de montaña.'],['Oriental','Incluye altiplanos y sectores donde se desarrollaron grandes centros urbanos.']]},
 clima:{t:'Clima y pisos térmicos',tag:'GEOGRAFÍA FÍSICA',body:'La altitud modifica la temperatura y, junto con la orientación de las montañas, la humedad y los vientos, produce una gran variedad de ambientes. Los pisos térmicos son una forma didáctica de relacionar altura y temperatura: cálido, templado, frío, páramo y, en las cumbres más altas, zonas nivales. No son fronteras rígidas y pueden variar según las condiciones locales.',heads:[['Páramo','Ecosistema de alta montaña con gran importancia para la regulación y almacenamiento de agua.'],['Altitud','Al subir disminuye generalmente la temperatura, aunque el clima real depende también de otros factores.'],['Vida humana','La altura influye en cultivos, vivienda, movilidad y actividades productivas.']]},
 agua:{t:'Hidrografía andina',tag:'GEOGRAFÍA FÍSICA',body:'Los ríos Magdalena y Cauca organizan dos de los grandes valles interandinos y han sido fundamentales para la historia económica y territorial de Colombia. A ellos se suman numerosos afluentes, quebradas, humedales y fuentes de montaña. El agua conecta ecosistemas, ciudades y actividades productivas, por lo que su calidad y disponibilidad son asuntos estratégicos.',heads:[['Cuencas','Una cuenca reúne el territorio que drena hacia un río principal y sus afluentes.'],['Usos','Abastecimiento, agricultura, energía, industria, ecosistemas y recreación dependen del agua.'],['Cuidado','La contaminación y la transformación de las cuencas pueden afectar a comunidades aguas abajo.']]},
 biodiversidad:{t:'Biodiversidad y ecosistemas',tag:'GEOGRAFÍA FÍSICA',body:'El gradiente de altura crea una sucesión de ambientes con especies adaptadas a condiciones diferentes. Bosques, bosques altoandinos, páramos, humedales y otros ecosistemas forman una red ecológica. La biodiversidad también sostiene servicios ecosistémicos como regulación hídrica, formación de suelos, polinización y oportunidades educativas y turísticas.',heads:[['Especies emblemáticas','El cóndor andino es uno de los símbolos de la alta montaña; también existen numerosas aves, mamíferos y plantas especializadas.'],['Páramos','Son ecosistemas estratégicos por su función en la regulación hídrica.'],['Presiones','Fragmentación, cambio de uso del suelo, contaminación y cambio climático pueden alterar estos sistemas.']]},
 poblacion:{t:'Población y territorio',tag:'GEOGRAFÍA HUMANA',body:'La Región Andina concentra una parte muy importante de la población colombiana y reúne grandes áreas metropolitanas junto con municipios pequeños y zonas rurales. La concentración urbana se relaciona con empleo, educación, servicios, infraestructura y procesos históricos de industrialización y administración.',heads:[['Urbano y rural','No son mundos separados: alimentos, agua, empleo, transporte y mercados conectan ambos espacios.'],['Densidad','Las zonas de alta concentración urbana contrastan con territorios montañosos de menor densidad.'],['Fuente','Para cifras actuales, utiliza los censos y proyecciones oficiales del DANE.']]},
 ciudades:{t:'Ciudades y redes urbanas',tag:'GEOGRAFÍA HUMANA',body:'Bogotá, Medellín, Cali, Bucaramanga, Manizales, Pereira, Armenia y Popayán son referentes urbanos del espacio andino. Cada ciudad cumple funciones distintas dentro de redes de transporte, comercio, educación, salud, industria y servicios. La geografía urbana se entiende mejor observando cómo una ciudad se relaciona con los municipios que la rodean.',heads:[['Metropolización','Las áreas urbanas pueden extender sus actividades y desplazamientos más allá de los límites administrativos.'],['Movilidad','La topografía influye en carreteras, transporte público, tiempos de viaje y expansión urbana.'],['Reto','El crecimiento requiere planificación para evitar desigualdades y ocupación de zonas de riesgo.']]},
 diversidad:{t:'Diversidad cultural',tag:'PERSONAS Y CULTURA',body:'La identidad andina se construye con múltiples historias y comunidades. Pueblos indígenas, comunidades campesinas, poblaciones afrodescendientes y habitantes urbanos aportan conocimientos, prácticas, lenguas, músicas, gastronomías, fiestas y formas de relación con el territorio. No existe una única “cultura andina”: hay diferencias profundas entre departamentos y localidades.',heads:[['Patrimonio','Fiestas, cocinas, artesanías, música y relatos locales forman parte de la memoria colectiva.'],['Territorio','Las prácticas culturales también reflejan clima, recursos, caminos y formas históricas de ocupación.'],['Valoración','Reconocer la diversidad implica evitar estereotipos y escuchar las voces de las comunidades.']]},
 urbanizacion:{t:'Urbanización',tag:'GEOGRAFÍA HUMANA',body:'El crecimiento de las ciudades andinas ha estado ligado a oportunidades económicas, migraciones, industrialización y expansión de servicios. Pero la urbanización también genera desafíos: presión sobre suelo y agua, movilidad, residuos, contaminación, vivienda y desigual acceso a oportunidades.',heads:[['Causa','Empleo, educación, servicios y conectividad atraen población hacia centros urbanos.'],['Consecuencia','La expansión puede aumentar la presión sobre ecosistemas periurbanos y áreas de riesgo.'],['Respuesta','Planificación, transporte sostenible, espacio público y protección ambiental ayudan a gestionar el crecimiento.']]},
 retosocial:{t:'Retos sociales',tag:'GEOGRAFÍA HUMANA',body:'Las desigualdades territoriales no afectan a todas las personas de la misma manera. Pueden existir brechas en ingresos, educación, salud, conectividad, transporte y acceso a servicios entre ciudades, periferias y zonas rurales. Analizar estos problemas exige considerar causas históricas y condiciones geográficas, no solo cifras aisladas.',heads:[['Enfoque territorial','Una solución útil en una gran ciudad puede no funcionar igual en una comunidad rural de montaña.'],['Conectividad','La distancia y el relieve pueden dificultar el acceso a oportunidades.'],['Participación','Las soluciones deben incorporar a las comunidades afectadas.']]},
 agro:{t:'Agricultura andina',tag:'ECONOMÍA',body:'La diversidad de alturas permite cultivar productos diferentes en espacios relativamente cercanos. Café, papa, maíz, frutas, hortalizas y otros productos forman parte de sistemas agrícolas diversos. La agricultura depende de suelo, agua, clima, vías, mercados, tecnología y condiciones de los productores.',heads:[['Café','Es un producto emblemático de varias zonas andinas y está asociado a cadenas de producción, transformación, comercio y turismo.'],['Riesgos','Variabilidad climática, precios, costos de transporte y cambios de uso del suelo pueden afectar a productores.'],['Oportunidad','La transformación de productos y los mercados diferenciados pueden agregar valor.']]},
 industria:{t:'Industria y transformación',tag:'ECONOMÍA',body:'Las ciudades andinas concentran buena parte de las actividades industriales y manufactureras del país. La cercanía a mercados, infraestructura, mano de obra y servicios favorece la localización de empresas, aunque la movilidad de mercancías y la disponibilidad de suelo también presentan retos.',heads:[['Cadenas','La industria conecta materias primas, transformación, logística, comercio y consumo.'],['Ciudades','Los principales centros urbanos funcionan como nodos productivos y de servicios.'],['Sostenibilidad','Eficiencia energética, gestión de residuos y tecnologías limpias reducen impactos.']]},
 servicios:{t:'Servicios y sector terciario',tag:'ECONOMÍA',body:'Educación, salud, comercio, finanzas, transporte, comunicaciones, turismo y servicios profesionales tienen gran peso en las ciudades andinas. El sector terciario también crea conexiones entre zonas rurales y urbanas mediante mercados, logística y servicios públicos.',heads:[['Conocimiento','Universidades, centros de investigación y empresas generan actividades basadas en conocimiento.'],['Comercio','Las ciudades funcionan como nodos donde confluyen productores y consumidores.'],['Digital','La conectividad permite nuevos servicios, pero la brecha digital sigue siendo un desafío.']]},
 turismo:{t:'Turismo de naturaleza y cultura',tag:'ECONOMÍA',body:'Los paisajes de montaña, páramos, parques, pueblos, gastronomía y patrimonio cultural ofrecen oportunidades turísticas. Un turismo responsable debe respetar la capacidad de carga, las normas de las áreas protegidas y las comunidades locales.',heads:[['Naturaleza','Senderismo, observación de aves y educación ambiental pueden aprovechar paisajes de alta montaña.'],['Cultura','Gastronomía, patrimonio y fiestas aportan experiencias vinculadas a la identidad local.'],['Responsabilidad','Visitar no debe significar deteriorar ecosistemas ni desplazar prácticas comunitarias.']]},
 conectividad:{t:'Conectividad y comercio',tag:'ECONOMÍA',body:'La ubicación central de la Región Andina la convierte en un gran espacio de conexión nacional. Sin embargo, las pendientes, montañas y condiciones geológicas hacen compleja la construcción y mantenimiento de vías. Carreteras, aeropuertos, sistemas urbanos y redes digitales son fundamentales para integrar territorios.',heads:[['Mercancías','Una vía eficiente puede reducir tiempos y costos entre productores, ciudades y mercados.'],['Montaña','La topografía exige puentes, túneles, viaductos y mantenimiento constante en algunos corredores.'],['Digital','Internet y telecomunicaciones amplían oportunidades educativas y económicas.']]}
};
function modal(d){let old=$('#proInfoModal');if(old)old.remove();const m=document.createElement('div');m.id='proInfoModal';m.innerHTML=`<article class="pro-dialog" role="dialog" aria-modal="true"><div class="pro-dialog-head"><div><span class="tag">${d.tag}</span><h2>${d.t}</h2></div><button class="pro-close" aria-label="Cerrar">×</button></div><div class="pro-copy"><p>${d.body}</p>${d.heads.map(x=>`<h3>${x[0]}</h3><p>${x[1]}</p>`).join('')}</div><div class="pro-facts">${d.heads.map(x=>`<div><b>+</b><span>${x[0]}</span></div>`).join('')}</div></article>`;document.body.appendChild(m);requestAnimationFrame(()=>m.classList.add('show'));m.addEventListener('click',e=>{if(e.target===m||e.target.closest('.pro-close')){m.classList.remove('show');setTimeout(()=>m.remove(),250)}});document.addEventListener('keydown',function esc(e){if(e.key==='Escape'){m.classList.remove('show');setTimeout(()=>m.remove(),250);removeEventListener('keydown',esc)}})}
function setupDetails(){ $$('[data-detail]').forEach(b=>{b.classList.add('pro-detail-btn');b.addEventListener('click',()=>{const d=details[b.dataset.detail];if(d)modal(d)})}) }
function setupReveal(){if(matchMedia('(prefers-reduced-motion: reduce)').matches){document.body.classList.add('pro-ready');return}const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('pro-ready');obs.unobserve(e.target)}}),{threshold:.08});$$('.reveal-section,.reveal').forEach(x=>obs.observe(x))}
function setupMusic(){const audio=$('#audioPlayer'),select=$('#trackSelect'),toggle=$('#musicToggle');if(!audio||!select||!toggle)return;const status=$('#musicStatus');let tries=0;const start=async()=>{try{const r=await fetch('music/music.json?pro='+Date.now(),{cache:'no-store'});const data=await r.json();const tracks=data.tracks||[];select.innerHTML=tracks.length?tracks.map((t,i)=>`<option value="${i}">${t.title||'Pista '+(i+1)}</option>`).join(''):'<option>Sin música</option>';if(tracks.length){let i=0;audio.src=tracks[i].src;audio.volume=Number($('#musicVolume')?.value||.3);status.textContent=tracks.length+' pistas del proyecto';select.onchange=()=>{audio.src=tracks[Number(select.value)].src;audio.play().catch(()=>{});toggle.textContent='⏸ Pausar'};toggle.onclick=()=>{if(audio.paused)audio.play().then(()=>toggle.textContent='⏸ Pausar').catch(()=>{});else{audio.pause();toggle.textContent='▶ Reproducir'}};audio.onended=()=>{const n=tracks.length;const next=(Number(select.value)+1)%n;select.value=String(next);audio.src=tracks[next].src;audio.play().catch(()=>{})}}}catch(e){if(++tries<3)setTimeout(start,800)}};start()}
function fixCrossword(){
 const candidates=$$('.crossword,#crossword,.game-crossword,[data-game="crossword"]');candidates.forEach(box=>{if(box.dataset.proFixed)return;box.dataset.proFixed='1';let text=box.innerText||'';if(!/cruci|horizontal|vertical/i.test(text))return;const title=box.querySelector('h3,h4,.game-title');if(title&&/cruci/i.test(title.textContent))title.textContent='Crucigrama · Región Andina';let lists=box.querySelectorAll('ol');lists.forEach((ol,i)=>{const h=document.createElement('h4');h.textContent=i===0?'Horizontal':'Vertical';ol.parentNode.insertBefore(h,ol);[...ol.children].forEach((li,j)=>{if(!li.querySelector('.pro-number'))li.insertAdjacentHTML('afterbegin',`<span class="pro-number">${j+1}.</span>`)})})});
}
function boot(){setupNav();setupDetails();setupReveal();setupMusic();fixCrossword();setTimeout(fixCrossword,1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();