(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const details={
ubicacion:['UBICACIÓN','¿Dónde está la Región Andina?','Se encuentra en la zona central de Colombia y está estructurada por los Andes. Es un territorio de montañas, valles, altiplanos y laderas donde se concentran importantes ciudades y actividades económicas.','La delimitación exacta puede variar según la fuente y el criterio utilizado; para el trabajo escolar conviene acompañarla con un mapa del IGAC.'],
relieve:['RELIEVE','Tres cordilleras','Los Andes colombianos se dividen en las cordilleras Occidental, Central y Oriental. Entre ellas se encuentran valles interandinos, cañones, mesetas, altiplanos y laderas.','El relieve condiciona caminos, asentamientos, agricultura y acceso a servicios.'],
clima:['CLIMA','Altura, temperatura y pisos térmicos','La altitud modifica la temperatura y ayuda a explicar los pisos térmicos. En la Región Andina aparecen ambientes cálidos, templados, fríos y de alta montaña.','Los pisos térmicos son una herramienta geográfica para relacionar altura, clima, vegetación y actividades humanas; no son fronteras rígidas.'],
agua:['HIDROGRAFÍA','Agua que conecta territorios','Los valles de los ríos Magdalena y Cauca son elementos fundamentales del paisaje andino. Las cuencas sostienen ecosistemas, agricultura, población y distintas actividades productivas.','El agua también enfrenta presiones por contaminación, transformación del territorio y cambios en su disponibilidad.'],
biodiversidad:['BIODIVERSIDAD','Páramos, bosques y vida','La variedad de alturas crea numerosos ambientes. Los páramos y bosques de montaña albergan especies adaptadas a condiciones muy diferentes.','La conservación de estos ecosistemas es clave para biodiversidad y regulación hídrica.'],
poblacion:['POBLACIÓN','Una región densamente habitada','El Atlas Estadístico del DANE registró cerca del 70,1 % de la población nacional en la delimitación regional de 2005. Es un dato histórico de referencia, no una cifra actual.','Para actualizar cifras, consulta las publicaciones y censos más recientes del DANE.'],
ciudades:['CIUDADES','Red urbana andina','Bogotá, Medellín, Cali, Bucaramanga, Manizales, Pereira, Armenia y Popayán son ciudades destacadas dentro del espacio andino o de su área de influencia.','Las ciudades concentran empleo, educación, comercio, servicios e infraestructura, y se conectan con municipios rurales.'],
diversidad:['DIVERSIDAD CULTURAL','Muchas identidades en una misma región','La diversidad cultural se expresa en gastronomía, música, fiestas, artesanías, formas de trabajo, memoria e historias locales.','No existe una única cultura andina: las expresiones cambian entre territorios y comunidades.'],
urbanizacion:['URBANIZACIÓN','Ciudades que crecen y transforman','El crecimiento urbano modifica el uso del suelo, la movilidad, la vivienda y la relación entre ciudad y campo.','La planificación territorial busca equilibrar crecimiento, servicios, ambiente y calidad de vida.'],
retosocial:['RETOS SOCIALES','Desigualdad y oportunidades','Persisten diferencias territoriales en ingresos, conectividad, acceso a servicios y oportunidades educativas y laborales.','Analizar estas diferencias ayuda a proponer soluciones adaptadas a cada territorio.'],
agro:['AGRICULTURA','Producir desde la montaña','La agricultura andina incluye café y una amplia variedad de cultivos según altura, suelo y clima. La producción se relaciona con mercados urbanos y redes de transporte.','La agricultura enfrenta retos como costos de transporte, variabilidad climática y acceso desigual a tecnología y mercados.'],
industria:['INDUSTRIA','Transformar y agregar valor','Las ciudades andinas concentran buena parte de las actividades industriales y de transformación de alimentos, manufacturas y otros bienes.','La industria depende de energía, mano de obra, infraestructura, mercados y conectividad.'],
servicios:['SERVICIOS','La economía de las ciudades','Comercio, educación, salud, finanzas, transporte, tecnología y otros servicios tienen un peso importante en la economía regional.','Las ciudades funcionan como nodos que conectan actividades rurales, industriales y comerciales.'],
turismo:['TURISMO','Naturaleza + cultura','Paisajes de montaña, pueblos, gastronomía, patrimonio y experiencias de naturaleza convierten al turismo en una actividad complementaria para muchos territorios.','El turismo responsable debe cuidar ecosistemas, patrimonio y beneficios para las comunidades locales.'],
conectividad:['CONECTIVIDAD','Mover personas y productos','La topografía montañosa hace que carreteras, túneles, puentes y corredores logísticos sean esenciales para conectar ciudades y zonas rurales.','La conectividad puede reducir tiempos y costos, pero también requiere inversión, mantenimiento y planificación.'],
gastronomia:['GASTRONOMÍA','Sabores con territorio','Platos y productos como ajiaco, tamales, lechona y café forman parte de distintas tradiciones culinarias de la región.','La cocina cambia entre departamentos y comunidades; cada receta cuenta una historia de ingredientes y territorio.'],
musica:['MÚSICA','Ritmos y memoria','La música tradicional y popular acompaña fiestas, encuentros y relatos locales. Instrumentos, ritmos y repertorios varían entre territorios.','La música también funciona como forma de memoria e identidad.'],
artesanias:['ARTESANÍAS','Oficios que cuentan historias','Tejidos, cerámica, madera y otros oficios conservan técnicas, materiales y conocimientos transmitidos entre generaciones.','Valorar el trabajo artesanal también significa reconocer a sus comunidades y creadores.'],
fiestas:['FIESTAS','Territorio en celebración','Las celebraciones regionales reúnen música, gastronomía, símbolos, historia y participación comunitaria.','Cada fiesta tiene un contexto propio y expresa identidades locales.'],
aguaReto:['DESAFÍO 01','Presión sobre el agua','La contaminación, transformación de ecosistemas y cambios en la disponibilidad pueden afectar fuentes y usuarios.','Respuesta posible: proteger cuencas, mejorar tratamiento, reducir contaminación y fortalecer educación y gestión comunitaria.'],
deforestacion:['DESAFÍO 02','Pérdida de ecosistemas','La transformación del suelo, expansión de actividades productivas y otras presiones pueden reducir bosques y hábitats.','Respuesta posible: restauración, protección de áreas estratégicas y producción compatible con la conservación.'],
desigualdad:['DESAFÍO 03','Desigualdad territorial','No todos los municipios tienen las mismas oportunidades de conectividad, empleo, educación o servicios.','Respuesta posible: inversión focalizada, planificación territorial y fortalecimiento de oportunidades locales.']};
const modal=$('#modal'),mTitle=$('#modalTitle'),mBody=$('#modalBody'),mEye=$('#modalEyebrow');
function openModal(key){const d=details[key];if(!d)return;mEye.textContent=d[0];mTitle.textContent=d[1];mBody.innerHTML=`<p>${d[2]}</p><div class="modal-highlight"><b>Para analizar</b><p>${d[3]}</p></div>`;modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
$('#modalClose').onclick=closeModal;$('.modal-backdrop').onclick=closeModal;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
$$('[data-detail]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.detail)));
const altData={calido:['Cálido','Menor altitud y temperaturas generalmente más altas. Son frecuentes cultivos tropicales y paisajes de ladera.'],templado:['Templado','Alturas intermedias con temperaturas moderadas. Son comunes cultivos como café en varias zonas.'],frio:['Frío','Mayor altitud, temperaturas más bajas y paisajes de montaña donde aparecen cultivos adaptados al clima.'],paramo:['Páramo','Ecosistemas de alta montaña fundamentales para biodiversidad y regulación del agua.']};
$$('[data-alt]').forEach(b=>b.addEventListener('click',()=>{const d=altData[b.dataset.alt];$$('[data-alt]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#altitudeInfo').innerHTML=`<b>${d[0]}</b><span>${d[1]}</span>`}));
const econ={primario:['01','SECTOR PRIMARIO','Campo, recursos y producción','Agricultura, ganadería y minería forman parte de la economía regional. El café es un producto emblemático de varias zonas andinas.',['☕ Café','🌱 Agricultura','🐄 Ganadería','⛏️ Minería']],secundario:['02','SECTOR SECUNDARIO','Transformar materias y crear bienes','La industria y la transformación de alimentos y manufacturas se concentran especialmente en centros urbanos conectados con mercados regionales.',['🏭 Industria','🥫 Alimentos','⚙️ Manufactura','📦 Transformación']],terciario:['03','SECTOR TERCIARIO','Servicios, comercio y turismo','Comercio, transporte, educación, salud, tecnología y turismo conectan personas y territorios y tienen gran peso en las ciudades.',['🛒 Comercio','🚍 Transporte','🎓 Educación','🏞️ Turismo']]};
$$('[data-econ]').forEach(b=>b.addEventListener('click',()=>{const d=econ[b.dataset.econ];$$('[data-econ]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#econInfo').innerHTML=`<div class="econ-number">${d[0]}</div><div><span class="eyebrow">${d[1]}</span><h3>${d[2]}</h3><p>${d[3]}</p><div class="chip-row">${d[4].map(x=>`<span>${x}</span>`).join('')}</div></div>`}));
const navLinks=$$('#mainNav a');const sections=navLinks.map(a=>$(a.getAttribute('href'))).filter(Boolean);const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-35% 0px -55% 0px',threshold:0});sections.forEach(s=>observer.observe(s));
const panel=$('#customPanel');$('#customizeBtn').onclick=()=>{panel.classList.toggle('show');panel.setAttribute('aria-hidden',String(!panel.classList.contains('show')))};$('#closeCustom').onclick=()=>{panel.classList.remove('show');panel.setAttribute('aria-hidden','true')};
$('#themeSelect').onchange=e=>{document.body.classList.remove('theme-night','theme-earth');if(e.target.value==='night')document.body.classList.add('theme-night');if(e.target.value==='earth')document.body.classList.add('theme-earth')};$('#fontScale').oninput=e=>document.documentElement.style.setProperty('--scale',e.target.value);$('#motionToggle').onchange=e=>document.body.classList.toggle('no-motion',!e.target.checked);$('#contrastToggle').onchange=e=>document.body.classList.toggle('high-contrast',e.target.checked);
const audio=$('#audioPlayer'),track=$('#trackSelect'),musicStatus=$('#musicStatus');let tracks=[],userUrls=[];function addTrack(title,src){const o=document.createElement('option');o.value=src;o.textContent=title;track.appendChild(o);tracks.push({title,src})}async function loadMusic(){try{const r=await fetch('music/music.json');const j=await r.json();(j.tracks||[]).forEach(x=>addTrack(x.title,x.src));musicStatus.textContent=tracks.length?`${tracks.length} pistas`:'Sin pistas'}catch(e){musicStatus.textContent='Lista no disponible'}}loadMusic();track.onchange=()=>{if(!track.value){audio.pause();audio.removeAttribute('src');return}audio.src=track.value;audio.load()};$('#musicToggle').onclick=()=>{if(!audio.src&&track.options.length>1)track.selectedIndex=1;if(!audio.src)return;if(audio.paused){audio.play().catch(()=>{});$('#musicToggle').textContent='❚❚ Pausar'}else{audio.pause();$('#musicToggle').textContent='▶ Reproducir'}};$('#musicLoop').onclick=()=>{audio.loop=!audio.loop;$('#musicLoop').textContent=audio.loop?'↻ Repetir: sí':'↻ Repetir: no'};$('#musicVolume').oninput=e=>audio.volume=e.target.value;$('#musicFiles').onchange=e=>[...e.target.files].forEach(f=>{const u=URL.createObjectURL(f);userUrls.push(u);addTrack(f.name,u)});
const quiz=[['¿Cuántas cordilleras principales forman los Andes colombianos?',['2','3','5'],1],['¿Qué río forma uno de los grandes valles interandinos?',['Amazonas','Cauca','Orinoco'],1],['¿Qué factor explica los pisos térmicos?',['La altitud','La distancia al mar únicamente','El tamaño de la ciudad'],0],['¿Cuál es un producto emblemático de varias zonas andinas?',['Café','Coco exclusivamente','Algodón exclusivamente'],0],['¿Qué caracteriza a los páramos?',['Ecosistemas de alta montaña','Zonas costeras','Desiertos'],0]];
function gameShell(title,sub,html){$('#gameArea').hidden=false;$('#gameArea').innerHTML=`<div class="game-live"><span class="eyebrow">${sub}</span><h3>${title}</h3>${html}<button class="btn btn-lime game-close" id="gameClose">Cerrar actividad</button></div>`;$('#gameClose').onclick=()=>{$('#gameArea').hidden=true;$('#gameArea').innerHTML='';$('#juegos').scrollIntoView({behavior:'smooth'})}}
function startQuiz(){let i=0,score=0;const render=()=>{if(i>=quiz.length){gameShell('¡Reto terminado!','RESULTADO',`<div class="modal-highlight"><h3>${score} / ${quiz.length}</h3><p>${score===quiz.length?'Excelente: dominas el recorrido.':score>=3?'Muy bien. Revisa las secciones para reforzar lo que faltó.':'Buen intento. Vuelve a explorar y repite el reto.'}</p></div>`);return}const q=quiz[i];gameShell('Quiz Andino',`PREGUNTA ${i+1} DE ${quiz.length}`,`<div class="quiz-question"><h3>${q[0]}</h3><div class="quiz-options">${q[1].map((x,k)=>`<button data-answer="${k}">${x}</button>`).join('')}</div></div>`);$$('[data-answer]').forEach(b=>b.onclick=()=>{const ok=+b.dataset.answer===q[2];if(ok){score++;b.classList.add('correct')}else{b.classList.add('wrong');$$('[data-answer]')[q[2]].classList.add('correct')}$$('[data-answer]').forEach(x=>x.disabled=true);const n=document.createElement('button');n.className='btn btn-lime quiz-next';n.textContent=i===quiz.length-1?'Ver resultado':'Siguiente →';$('#gameArea .game-live').appendChild(n);n.onclick=()=>{i++;render()}})};render()}
function startMemory(){const pairs=[['Café','Agricultura'],['Páramo','Agua'],['Cordillera','Relieve'],['Ciudad','Servicios']];let deck=pairs.flatMap((p,i)=>[{t:p[0],p:i},{t:p[1],p:i}]).sort(()=>Math.random()-.5),first=null,lock=false,found=0;gameShell('Memoria de conceptos','RETO 02',`<p>Encuentra las parejas que pertenecen al mismo concepto.</p><div class="memory-board">${deck.map((x,i)=>`<button class="memory-card" data-card="${i}">?</button>`).join('')}</div>`);$$('[data-card]').forEach((b,i)=>b.onclick=()=>{if(lock||b.classList.contains('matched')||b===first)return;b.textContent=deck[i].t;b.classList.add('flipped');if(!first){first=b;return}lock=true;const j=+first.dataset.card;if(deck[j].p===deck[i].p){first.classList.add('matched');b.classList.add('matched');found++;first=null;lock=false;if(found===pairs.length){const p=document.createElement('p');p.className='modal-highlight';p.textContent='¡Todas las parejas encontradas!';$('#gameArea .game-live').appendChild(p)}}else setTimeout(()=>{first.textContent='?';b.textContent='?';first.classList.remove('flipped');b.classList.remove('flipped');first=null;lock=false},650)})}
$$('[data-game]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.game==='quiz')startQuiz();else if(b.dataset.game==='memory')startMemory();else if(b.dataset.game==='crossword')startCrossword()}));
function startCrossword(){const words=[['ANDES','Cordillera que atraviesa el occidente de Sudamérica.'],['CAUCA','Río de un importante valle interandino.'],['CAFE','Producto emblemático de varias zonas andinas.'],['PARAMO','Ecosistema de alta montaña.'],['BOGOTA','Capital ubicada en el altiplano de la cordillera Oriental.']];const size=13,grid=Array.from({length:size},()=>Array(size).fill(null)),placed=[];function put(word,row,col,dir){for(let i=0;i<word.length;i++)grid[row+(dir==='v'?i:0)][col+(dir==='h'?i:0)]=word[i];placed.push({word,row,col,dir})}put('ANDES',2,2,'h');put('CAFE',0,4,'v');put('CAUCA',4,2,'h');put('PARAMO',2,4,'v');put('BOGOTA',8,4,'h');let html='<p>Escribe las respuestas en las casillas blancas. Las palabras se cruzan como en un crucigrama clásico.</p><div class="crossword-wrap"><div class="crossword-grid">';for(let r=0;r<size;r++)for(let c=0;c<size;c++){const ch=grid[r][c];if(ch){html+=`<input maxlength="1" class="cross-cell" data-r="${r}" data-c="${c}" aria-label="casilla ${r+1}-${c+1}">`}else html+='<span class="cross-black"></span>'}html+='</div><div class="cross-clues"><b>Horizontales</b><ol><li>ANDES</li><li>CAUCA</li><li>BOGOTA</li></ol><b>Verticales</b><ol><li>CAFE</li><li>PARAMO</li></ol></div></div><button class="btn btn-lime" id="checkCross">Comprobar</button><span id="crossResult"></span>';gameShell('Crucigrama clásico','RETO 03',html);$('#checkCross').onclick=()=>{let ok=0,total=0;grid.forEach((row,r)=>row.forEach((ch,c)=>{if(ch){total++;const el=$(`.cross-cell[data-r="${r}"][data-c="${c}"]`);if(el&&el.value.toUpperCase()===ch)ok++}}));$('#crossResult').textContent=` ${ok}/${total} casillas correctas.`}}
$('#saveReflection').onclick=()=>{const v=$('#reflectionInput').value.trim();$('#reflectionSaved').textContent=v?'✓ Idea guardada en esta sesión.':'Escribe una idea primero.'};
window.addEventListener('load',()=>setTimeout(()=>$('#loader').classList.add('hide'),350));setTimeout(()=>$('#loader')?.classList.add('hide'),1800);
})();