(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const quiz=[
 ['¿Qué tres cordilleras forman los Andes colombianos?',['Occidental, Central y Oriental','Norte, Centro y Sur','Central, Caribe y Pacífica'],0],
 ['¿Qué ecosistema de alta montaña es clave para la regulación del agua?',['Páramo','Manglar','Arrecife'],0],
 ['¿Qué río recorre uno de los grandes valles interandinos?',['Cauca','Meta','Atrato'],0],
 ['¿Cuál de estas ciudades pertenece a la Región Andina?',['Bogotá','Leticia','Riohacha'],0],
 ['¿Qué producto es emblemático de varias zonas andinas?',['Café','Coco','Atún'],0]
];
const challenge=[
 ['ALTURA','Relaciona la altitud con cambios de temperatura, vegetación y formas de vida.'],
 ['AGUA','Explica por qué los páramos y las cuencas son importantes para personas y ecosistemas.'],
 ['CIUDADES','Relaciona ciudades, vías, empleo y servicios con la organización del territorio.'],
 ['ECONOMÍA','Completa: clima + suelo + trabajo + infraestructura + mercado = ________.']
];
const esc=t=>String(t).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function closeGame(){const m=$('#andinaGameModal');if(m){m.classList.remove('show');setTimeout(()=>m.remove(),220)}}
function openGame(title,body){closeGame();const m=document.createElement('div');m.id='andinaGameModal';m.className='modal';m.innerHTML=`<div class="modal-box game-modal-box"><button class="game-close" aria-label="Cerrar">×</button><span class="tag">ACTIVIDAD · REGIÓN ANDINA</span><h2>${esc(title)}</h2><div class="game-content">${body}</div></div>`;document.body.appendChild(m);requestAnimationFrame(()=>m.classList.add('show'));m.addEventListener('click',e=>{if(e.target===m||e.target.closest('.game-close'))closeGame()});return $('.game-content',m)}
function startQuiz(){let i=0,score=0;const render=()=>{const q=quiz[i];const host=openGame('Quiz Andino',`<p class="game-count">Pregunta ${i+1} de ${quiz.length}</p><h3>${esc(q[0])}</h3><div class="quiz-options">${q[1].map((x,n)=>`<button data-answer="${n}">${esc(x)}</button>`).join('')}</div><div class="game-feedback" aria-live="polite"></div>`);$$('.quiz-options button',host).forEach(b=>b.onclick=()=>{const ok=Number(b.dataset.answer)===q[2];if(ok)score++;$$('.quiz-options button',host).forEach(x=>{x.disabled=true;if(Number(x.dataset.answer)===q[2])x.classList.add('correct')});$('.game-feedback',host).innerHTML=ok?'<b>✓ Correcto.</b> ¡Buen trabajo!':'<b>Revisa:</b> la respuesta correcta está marcada.';const next=document.createElement('button');next.className='primary game-next';next.textContent=i===quiz.length-1?'Ver resultado':'Siguiente';next.onclick=()=>{i++;i<quiz.length?render():finishQuiz()};host.appendChild(next)})};const finishQuiz=()=>{const host=openGame('Resultado del quiz',`<div class="game-result"><strong>${score}/${quiz.length}</strong><p>${score===quiz.length?'¡Dominio andino!':score>=3?'Muy bien. Ya reconoces varias claves de la región.':'Buen comienzo. Vuelve a las secciones y prueba de nuevo.'}</p><button class="primary" id="retryQuiz">↻ Intentarlo otra vez</button></div>`);$('#retryQuiz',host).onclick=startQuiz};render()}
function startChallenge(){let order=[...challenge].sort(()=>Math.random()-.5),i=0;const next=()=>{const item=order[i];const host=openGame('Desafío rápido',`<p class="game-count">Reto ${i+1} de ${order.length}</p><div class="challenge-prompt"><b>${esc(item[0])}</b><p>${esc(item[1])}</p></div><textarea id="challengeAnswer" rows="4" placeholder="Escribe tu respuesta con tus propias palabras…"></textarea><button class="primary" id="checkChallenge">Comprobar</button><div class="game-feedback" aria-live="polite"></div>`);$('#checkChallenge',host).onclick=()=>{const a=$('#challengeAnswer',host).value.trim(),f=$('.game-feedback',host);if(a.length<12){f.innerHTML='<b>Amplía tu respuesta.</b> Escribe una idea desarrollada.';return}f.innerHTML='<b>✓ Respuesta registrada.</b> Lo importante es justificar la relación territorial.';const b=document.createElement('button');b.className='primary game-next';b.textContent=i===order.length-1?'Terminar':'Siguiente reto';b.onclick=()=>{i++;i<order.length?next():openGame('Desafío completado','<div class="game-result"><strong>¡Buen trabajo!</strong><p>Relacionaste territorio, población, agua y economía desde tu propio razonamiento.</p></div>')};host.appendChild(b)}};next()}
function boot(){$$('.game-card [data-game]').forEach(btn=>btn.addEventListener('click',()=>{const mode=btn.dataset.game;if(mode==='quiz')startQuiz();else if(mode==='challenge')startChallenge();else if(mode==='crossword'){const cross=$('#proCrossword');if(cross)cross.scrollIntoView({behavior:'smooth',block:'center'})}}))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
