(()=>{
'use strict';
if(window.__ANDINA_CORDILLERAS_REAL__)return;
window.__ANDINA_CORDILLERAS_REAL__=true;
const DATA={
  occidental:{name:'Cordillera Occidental',place:'Pico Pance · Farallones de Cali',img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/76001_%2818%29Pico_Pance.jpg/960px-76001_%2818%29Pico_Pance.jpg',source:'https://commons.wikimedia.org/wiki/File:76001_(18)Pico_Pance.jpg',credit:'Foto: Wikimedia Commons · Pico Pance · CC BY-SA 4.0'},
  central:{name:'Cordillera Central',place:'Paisaje de la Cordillera Central · Quindío',img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Cordillera_Central_-_Quind%C3%ADo_-_Colombia_%2814749295421%29.jpg/960px-Cordillera_Central_-_Quind%C3%ADo_-_Colombia_%2814749295421%29.jpg',source:'https://commons.wikimedia.org/wiki/File:Cordillera_Central_-_Quind%C3%ADo_-_Colombia_(14749295421).jpg',credit:'Foto: Alejandro Bayer Tamayo · Wikimedia Commons · CC BY-SA 2.0'},
  oriental:{name:'Cordillera Oriental',place:'Paisaje de la Cordillera Oriental · Colombia',img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Cordillera_oriental_Colombia.jpg/960px-Cordillera_oriental_Colombia.jpg',source:'https://commons.wikimedia.org/wiki/File:Cordillera_oriental_Colombia.jpg',credit:'Foto: Mpbonillap · Wikimedia Commons · CC BY-SA 4.0'}
};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function addStyle(){if($('#cordilleras-real-css'))return;const l=document.createElement('link');l.id='cordilleras-real-css';l.rel='stylesheet';l.href='./cordilleras-real.css?v=20260915-1';document.head.appendChild(l)}
function build(){if($('#cordilleras-reales'))return;const fisica=$('#fisica');if(!fisica)return;const s=document.createElement('section');s.id='cordilleras-reales';s.className='section cordilleras-real-section';s.innerHTML=`<div class="section-head"><div><span class="eyebrow">GEOGRAFÍA FÍSICA · 3 CORDILLERAS</span><h2>Las tres cordilleras, <em>en fotografías reales.</em></h2></div><p>Ya no son siluetas dibujadas: toca Occidental, Central u Oriental y cambia la fotografía para explorar un paisaje real de cada cordillera.</p></div><div class="cordillera-switcher" role="tablist" aria-label="Seleccionar cordillera"><button type="button" class="active" data-cordillera="occidental">Occidental</button><button type="button" data-cordillera="central">Central</button><button type="button" data-cordillera="oriental">Oriental</button></div><div class="cordillera-view"><figure><img id="cordilleraPhoto" alt="Paisaje real de la Cordillera Occidental" loading="lazy"><figcaption id="cordilleraCaption"></figcaption></figure><div class="cordillera-info"><span class="eyebrow" id="cordilleraEyebrow">CORDILLERA OCCIDENTAL</span><h3 id="cordilleraTitle">Cordillera Occidental</h3><p id="cordilleraPlace"></p><a id="cordilleraSource" target="_blank" rel="noopener">Ver fuente y licencia ↗</a></div></div>`;fisica.parentNode.insertBefore(s,fisica.nextSibling);$$('[data-cordillera]',s).forEach(b=>b.addEventListener('click',()=>show(b.dataset.cordillera)));show('occidental')}
function show(k){const d=DATA[k];if(!d)return;$$('[data-cordillera]').forEach(b=>{const on=b.dataset.cordillera===k;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on))});const img=$('#cordilleraPhoto');if(img){img.src=d.img;img.alt=`Paisaje real de la ${d.name}`}$('#cordilleraEyebrow').textContent=d.name.toUpperCase();$('#cordilleraTitle').textContent=d.name;$('#cordilleraPlace').textContent=d.place;$('#cordilleraCaption').innerHTML=`${d.credit} · <a href="${d.source}" target="_blank" rel="noopener">fuente</a>`;$('#cordilleraSource').href=d.source}
function removeHeroShapes(){ $$('.hero-art .mountain').forEach(m=>{m.style.display='none'});const art=$('.hero-art');if(art)art.classList.add('real-mountains-replaced') }
function run(){addStyle();build();removeHeroShapes()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,1900),{once:true});else setTimeout(run,1900);
})();
