(()=>{
'use strict';
const ROOT=document.documentElement;
const KEY='andina-modo';
const originals=new WeakMap();
const simple={
 'CIENCIAS SOCIALES · GRADO 11°':'CIENCIAS SOCIALES · 11°',
 'Una ventana digital a las montañas, los páramos, las ciudades, los sabores, los oficios y los desafíos del corazón de Colombia.':'Conoce las montañas, ciudades, naturaleza y cultura de la Región Andina.',
 'Empezar recorrido ↓':'Empezar ↓','LA IDEA':'LA IDEA','No memorices datos sueltos.':'Aprende con conexiones.','Conecta territorio y vida.':'Territorio y vida.','Montañas, valles y altiplanos':'Montañas y valles','Cuencas y ecosistemas de alta montaña':'Ríos y ecosistemas','Producción, ciudades y cultura':'Trabajo, ciudades y cultura',
 '02 · GEOGRAFÍA FÍSICA':'02 · GEOGRAFÍA FÍSICA','La altura cambia todo.':'La altura cambia muchas cosas.','Explora ubicación, relieve, clima, agua y biodiversidad. La información se acompaña de imágenes y recursos visuales.':'Aprende sobre montañas, clima, agua y naturaleza.','¿Dónde está?':'¿Dónde queda?','Las cordilleras':'Montañas','Ríos y cuencas':'Ríos','Páramos y bosques':'Naturaleza','Un territorio de contrastes':'Un territorio con muchas formas','Elige una altura':'Elige una altura','Ahora sí: cambiar una altura cambia toda la experiencia, no solo una frase.':'Prueba una altura y mira qué cambia.','PAISAJE ANDINO':'PAISAJE ANDINO','PISOS TÉRMICOS':'PISOS TÉRMICOS','Clima':'Clima','Ecosistema':'Naturaleza','Actividad humana':'Personas y trabajo',
 '03 · GEOGRAFÍA HUMANA':'03 · GEOGRAFÍA HUMANA','Las montañas también se habitan.':'Las montañas también tienen gente.','Personas, ciudades, comunidades rurales y expresiones culturales construyen territorios diferentes.':'Aquí viven muchas personas y comunidades.','POBLACIÓN':'POBLACIÓN','RED URBANA':'CIUDADES','Ciudades que conectan territorios':'Ciudades conectadas','Diversidad cultural':'Culturas','Urbanización':'Ciudades y campo','Retos sociales':'Retos de las personas','Ver contexto →':'Ver más →',
 '04 · GEOGRAFÍA ECONÓMICA':'04 · ECONOMÍA','Del territorio a lo que producimos.':'¿Qué producimos?','La economía se entiende mejor cuando conectamos recursos, transformación, servicios, transporte y consumo.':'Mira cómo el territorio se relaciona con el trabajo y los servicios.','SECTOR PRIMARIO':'SECTOR PRIMARIO','SECTOR SECUNDARIO':'SECTOR SECUNDARIO','SECTOR TERCIARIO':'SECTOR TERCIARIO','Campo, recursos y producción':'Trabajo del campo','Transformar materias y crear bienes':'Crear productos','Servicios, comercio y turismo':'Servicios y turismo','Producto emblemático':'Producto importante','Agricultura de altura':'Cultivos de montaña','Ciudades y conectividad':'Ciudades y servicios','Naturaleza + cultura':'Naturaleza y cultura',
 '05 · CULTURA Y DIVERSIDAD':'05 · CULTURA','Lo andino también se saborea y se escucha.':'La cultura andina se come y se escucha.','Las expresiones culturales cambian entre territorios. Aquí cada tarjeta funciona como una pequeña ventana.':'Hay comidas, músicas, fiestas y artesanías diferentes.','Ajiaco, tamales, café y más':'Comidas y bebidas','Tiple, bambuco y memoria':'Música andina','Oficios y materiales':'Artesanías','Encuentro e identidad':'Fiestas','Vestuario':'Ropa tradicional','Instrumentos':'Instrumentos','El tiple es un símbolo musical colombiano':'El tiple es un instrumento tradicional','Un producto ligado al paisaje y al trabajo rural':'Producto ligado al campo','Ícono de los ecosistemas de páramo':'Planta de los páramos',
 '06 · PROBLEMÁTICAS Y DESAFÍOS':'06 · DESAFÍOS','Comprender para proponer.':'Entender para ayudar.','Cada reto incluye problema, causas, consecuencias, afectados y posibles respuestas.':'Conoce algunos problemas y piensa en soluciones.','Presión sobre el agua':'Cuidemos el agua','Fuentes, contaminación y disponibilidad':'Agua limpia y disponible','Pérdida de ecosistemas':'Cuidemos la naturaleza','Bosques, páramos y transformación':'Bosques y páramos','Desigualdad territorial':'Oportunidades para todos','Servicios y oportunidades':'Servicios y oportunidades','ESPACIO DE REFLEXIÓN':'PIENSA Y PROPÓN','Diseña una solución':'Piensa una solución','Escribe una idea y conviértela en una propuesta concreta.':'Escribe una idea para ayudar.','Mi propuesta…':'Mi idea…','Guardar propuesta':'Guardar idea',
 '07 · ACTIVIDADES INTERACTIVAS':'07 · JUEGOS','Aprende jugando.':'¡Aprende jugando!','Explora cinco experiencias nuevas: mapa, viaje, conexiones, misterio y decisiones comunitarias.':'Juega y aprende sobre la Región Andina.','Cerrar actividad':'Cerrar juego','Repetir actividad':'Jugar otra vez','Tiempo agotado':'Se acabó el tiempo','Se acabó el tiempo. ¡Puedes intentarlo otra vez!':'Se acabó el tiempo. ¡Inténtalo otra vez!','Excelente dominio de la Región Andina.':'¡Muy bien!','Buen trabajo: revisa las explicaciones y vuelve a intentarlo.':'¡Buen trabajo! Puedes intentarlo otra vez.','Encuentra cada pareja: símbolo + concepto relacionado con la Región Andina.':'Encuentra las parejas.','Completa las palabras. Puedes escribir en mayúsculas o minúsculas y comprobar cuando quieras.':'Completa las palabras y comprueba tus respuestas.','Selecciona la primera y última letra de una palabra. Se aceptan líneas horizontales, verticales y diagonales.':'Busca las palabras en la cuadrícula.','PISTAS':'PISTAS','Comprobar':'Comprobar',
 '08 · PRODUCTOS DEL GRUPO':'08 · PRODUCTOS','También creamos.':'También creamos.','Aquí quedarán integrados el video, podcast, infografías y presentación exigidos por el proyecto.':'Aquí están nuestros materiales del proyecto.','Video original':'Video','Podcast':'Podcast','Infografías':'Infografías','PowerPoint':'Presentación','Agregar video':'Agregar video','Agregar audio':'Agregar audio','Agregar infografías':'Agregar infografías','Agregar presentación':'Agregar presentación'
};
function transformText(node){
 if(node.nodeType!==3)return;
 if(!originals.has(node))originals.set(node,node.nodeValue);
 const src=originals.get(node);
 let out=src;
 if(ROOT.classList.contains('modo-ninos')){
   Object.keys(simple).forEach(k=>{if(out.includes(k))out=out.split(k).join(simple[k])});
 }
 node.nodeValue=out;
}
function translate(root=document.body){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode())transformText(n)}
function restore(root=document.body){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){const old=originals.get(n);if(old!==undefined)n.nodeValue=old}}
function setMode(k){const child=k==='ninos';ROOT.classList.toggle('modo-ninos',child);localStorage.setItem(KEY,child?'ninos':'normal');document.body?.setAttribute('data-modo',child?'ninos':'normal');const b=document.getElementById('modeSwitch');if(b){b.setAttribute('aria-pressed',String(child));b.querySelector('.mode-label').textContent=child?'Modo normal':'Modo niños';b.querySelector('.mode-icon').textContent=child?'📘':'🧸'}child?translate():restore()}
function addButton(){const nav=document.querySelector('.nav');if(!nav||document.getElementById('modeSwitch'))return;const b=document.createElement('button');b.id='modeSwitch';b.className='mode-switch';b.type='button';b.setAttribute('aria-label','Cambiar entre modo normal y modo niños');b.innerHTML='<span class="mode-icon">🧸</span><span class="mode-label">Modo niños</span>';b.addEventListener('click',()=>setMode(ROOT.classList.contains('modo-ninos')?'normal':'ninos'));nav.appendChild(b)}
function init(){addButton();setMode(localStorage.getItem(KEY)==='ninos'?'ninos':'normal');const observer=new MutationObserver(muts=>{if(!ROOT.classList.contains('modo-ninos'))return;muts.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1)translate(n);else if(n.nodeType===3)transformText(n)}))});observer.observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
