(()=>{
'use strict';
const ROOT='#andina-other-games';
const css=`
#andina-other-games{margin-top:14px}
.og-panel{position:relative;overflow:hidden;border-radius:26px;background:linear-gradient(145deg,#173e32,#0b2921);color:#fff;box-shadow:0 22px 55px #0005;border:1px solid #ffffff1c;animation:ogIn .45s ease both}
.og-panel:before{content:'';position:absolute;width:260px;height:260px;right:-110px;top:-110px;border-radius:50%;background:#dced9230;filter:blur(2px);pointer-events:none}
.og-head{position:relative;padding:25px 24px 18px;display:flex;justify-content:space-between;gap:18px;align-items:flex-start;flex-wrap:wrap}
.og-kicker{font-size:.72rem;letter-spacing:.16em;font-weight:900;opacity:.68}.og-head h3{margin:5px 0 4px;font-size:clamp(1.55rem,4vw,2.35rem)}.og-head p{margin:0;opacity:.78;max-width:720px;line-height:1.45}.og-score{background:#dced92;color:#173e32;border-radius:16px;padding:10px 13px;font-weight:900;white-space:nowrap}
.og-body{position:relative;padding:0 24px 26px}.og-card{background:#fff;color:#173e32;border-radius:20px;padding:20px;box-shadow:0 14px 34px #0004}.og-card h4{margin:0 0 8px;font-size:1.25rem}.og-card p{line-height:1.45;margin:0 0 15px;opacity:.75}
.og-actions{display:flex;gap:10px;flex-wrap:wrap}.og-btn{border:0;border-radius:13px;padding:11px 15px;font-weight:900;cursor:pointer;background:#dced92;color:#173e32;transition:.2s}.og-btn:hover{transform:translateY(-2px)}.og-btn.secondary{background:#ffffff14;color:#fff;border:1px solid #ffffff35}
.og-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.og-tile{border:1px solid #d2dacf;border-radius:16px;background:#f8faf5;color:#173e32;padding:17px;text-align:left;cursor:pointer;min-height:118px;transition:.2s;position:relative;overflow:hidden}.og-tile:hover{transform:translateY(-4px);box-shadow:0 10px 22px #0002}.og-tile .og-icon{font-size:2rem;display:block;margin-bottom:8px}.og-tile b{display:block}.og-tile small{display:block;margin-top:4px;opacity:.65;line-height:1.35}.og-tile.correct{background:#dced92;border-color:#9ebd55}.og-tile.wrong{animation:ogShake .35s ease;background:#f0d1c7;border-color:#c98776}.og-pairs{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px}.og-pair{min-height:105px;border:2px solid #d2dacf;border-radius:16px;background:#f8faf5;color:#173e32;cursor:pointer;font-weight:900;padding:12px;text-align:center;transition:.2s}.og-pair:hover{transform:scale(1.025)}.og-pair.selected{border-color:#71934c;box-shadow:0 0 0 4px #71934c22}.og-pair.matched{background:#dced92;border-color:#9ebd55;pointer-events:none}.og-pair .og-icon{font-size:1.8rem;display:block;margin-bottom:6px}.og-pair small{display:block;font-weight:700;opacity:.65}
.og-meter{height:8px;background:#ffffff2d;border-radius:99px;overflow:hidden;margin:14px 0}.og-meter i{display:block;height:100%;background:#dced92;transition:width .3s}.og-choice-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.og-choice{border:1px solid #d2dacf;border-radius:15px;background:#f8faf5;color:#173e32;padding:15px;text-align:left;font-weight:800;cursor:pointer;min-height:80px;transition:.2s}.og-choice:hover{transform:translateY(-2px)}.og-choice.good{background:#dced92}.og-choice.bad{background:#f0d1c7}.og-feedback{min-height:27px;margin-top:12px;font-weight:900}.og-feedback.good{color:#4f741f}.og-feedback.bad{color:#9c3e31}.og-clues{display:grid;gap:9px;margin:14px 0}.og-clue{padding:12px 14px;border-radius:13px;background:#eef3e9;border-left:4px solid #71934c;color:#173e32;animation:ogSlide .35s ease both}.og-answer{display:flex;gap:9px;flex-wrap:wrap}.og-answer input{flex:1;min-width:190px;border:1px solid #bfc9bd;border-radius:13px;padding:12px 14px;font:inherit;color:#173e32}.og-result{margin-top:15px;padding:14px;border-radius:14px;background:#edf4df;color:#173e32;font-weight:800}
.og-final{padding:36px 18px;text-align:center}.og-final .big{font-size:3.5rem}.og-final h4{font-size:2rem;margin:6px 0}.og-final p{max-width:650px;margin:0 auto 17px;opacity:.78;line-height:1.5}
@keyframes ogIn{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:none}}@keyframes ogShake{25%{transform:translateX(-5px)}50%{transform:translateX(5px)}75%{transform:translateX(-3px)}}@keyframes ogSlide{from{opacity:0;transform:translateX(-12px)}to{opacity:1;transform:none}}
@media(max-width:800px){.og-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.og-pairs{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(max-width:560px){.og-head,.og-body{padding-left:14px;padding-right:14px}.og-grid,.og-choice-grid{grid-template-columns:1fr}.og-pairs{grid-template-columns:repeat(2,minmax(0,1fr))}.og-pair{min-height:92px}.og-score{width:100%;text-align:center}}
`;
const games={
 conecta:{
  title:'Conecta territorio',kicker:'RETO DE RELACIONES',intro:'Une cada elemento con su pareja territorial. No basta con acertar: descubre la relación que los conecta.',icon:'🔗',
  pairs:[['☕','Café','Economía rural'],['💧','Páramo','Regulación hídrica'],['🏙️','Bogotá','Servicios'],['🌿','Bosque andino','Biodiversidad'],['🚜','Agricultura','Uso del suelo'],['🎵','Bambuco','Cultura']],
  start(root){let deck=[];this.pairs.forEach((p,i)=>{deck.push({id:i,side:'a',icon:p[0],name:p[1],hint:'Elemento'});deck.push({id:i,side:'b',icon:'↔',name:p[2],hint:'Relación'})});deck=shuffle(deck);let first=null,locked=false,matched=0;root.innerHTML=card(this,'<div class="og-card"><h4>Forma las parejas</h4><p>Selecciona dos tarjetas. Si pertenecen a la misma relación, quedarán unidas.</p><div class="og-pairs" id="ogPairs">'+deck.map((x,n)=>`<button class="og-pair" data-n="${n}" data-id="${x.id}"><span class="og-icon">${x.icon}</span>${x.name}<small>${x.hint}</small></button>`).join('')+'</div><div class="og-feedback" id="ogFeedback"></div><div class="og-meter"><i id="ogMeter" style="width:0%"></i></div></div>');
   const buttons=[...root.querySelectorAll('.og-pair')];buttons.forEach(btn=>btn.onclick=()=>{if(locked||btn.classList.contains('matched')||btn===first)return;btn.classList.add('selected');if(!first){first=btn;return}locked=true;const ok=first.dataset.id===btn.dataset.id;const fb=root.querySelector('#ogFeedback');if(ok){first.classList.add('matched');btn.classList.add('matched');matched++;fb.textContent='¡Conexión correcta!';fb.className='og-feedback good';root.querySelector('#ogMeter').style.width=(matched/this.pairs.length*100)+'%';if(matched===this.pairs.length)setTimeout(()=>finish(root,'🎉','¡Territorio conectado!','Relacionaste economía, ambiente, población y cultura. Esa es la idea: los elementos del territorio no funcionan aislados.'),550);first=null;locked=false}else{fb.textContent='Casi. Busca la relación territorial que corresponde.';fb.className='og-feedback bad';setTimeout(()=>{first.classList.remove('selected');btn.classList.remove('selected');first=null;locked=false},500)}});
  }
 },
 misterio:{
  title:'Misterio Andino',kicker:'PISTAS + DEDUCCIÓN',intro:'Lee las pistas una por una y descubre qué lugar, paisaje o actividad está oculto.',icon:'🕵️',
  rounds:[
   {answer:'páramo',display:'el páramo',clues:['Estoy en la alta montaña.','Ayudo a regular y almacenar agua.','El frailejón es uno de mis símbolos.']},
   {answer:'café',display:'el café',clues:['Nací de un cultivo ligado a laderas y altitudes.','Mi cadena incluye producción, transformación y comercio.','Soy un producto emblemático del paisaje cafetero.']},
   {answer:'bogotá',display:'Bogotá',clues:['Soy una gran ciudad de la Cordillera Oriental.','Estoy en un altiplano.','Concentro servicios, instituciones y actividades económicas.']},
   {answer:'valle del cauca',display:'el Valle del Cauca',clues:['Soy un valle interandino.','El río Cauca atraviesa mi territorio.','La agricultura y las conexiones urbanas tienen gran importancia.']}
  ],
  start(root){let round=0,clue=0;const render=()=>{const r=this.rounds[round];root.innerHTML=card(this,`<div class="og-card"><h4>Misterio ${round+1} de ${this.rounds.length}</h4><p>Abre una pista, piensa y responde cuando estés listo.</p><div class="og-clues">${r.clues.slice(0,clue).map((c,i)=>`<div class="og-clue">Pista ${i+1}: ${c}</div>`).join('')}</div><div class="og-actions"><button class="og-btn" id="clueBtn">${clue<r.clues.length?'🔎 Ver pista':'✨ Resolver'}</button></div><div class="og-answer" style="margin-top:14px"><input id="mysteryInput" placeholder="Escribe tu respuesta…" autocomplete="off"><button class="og-btn" id="answerBtn">Comprobar</button></div><div class="og-feedback" id="mysteryFeedback"></div></div>`);root.querySelector('#clueBtn').onclick=()=>{if(clue<r.clues.length){clue++;render()}else root.querySelector('#mysteryInput').focus()};root.querySelector('#answerBtn').onclick=()=>check();root.querySelector('#mysteryInput').onkeydown=e=>{if(e.key==='Enter')check()};const check=()=>{const v=root.querySelector('#mysteryInput').value.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const ans=r.answer.normalize('NFD').replace(/[\u0300-\u036f]/g,'');const ok=v===ans||v.includes(ans)||ans.includes(v);const fb=root.querySelector('#mysteryFeedback');if(!v){fb.textContent='Escribe una respuesta primero.';return}if(ok){fb.textContent='¡Misterio resuelto!';fb.className='og-feedback good';setTimeout(()=>{round++;clue=0;if(round<this.rounds.length)render();else finish(root,'🔎','¡Caso resuelto!','Usaste pistas geográficas, ambientales, económicas y culturales para deducir el territorio.'},500)}else{fb.textContent='No todavía. Lee otra pista y vuelve a intentarlo.';fb.className='og-feedback bad'}}};render()}
 },
 decisiones:{
  title:'Decisiones comunitarias',kicker:'SIMULACIÓN DE TERRITORIO',intro:'Toma decisiones ante situaciones reales. Cada elección cambia el equilibrio entre ambiente, economía y bienestar.',icon:'🌱',
  scenarios:[
   {q:'Una comunidad cerca de un ecosistema de páramo necesita ingresos. ¿Qué opción ofrece un mejor equilibrio?',opts:[['Aumentar actividades sin controles.','Ambiente: -2, Economía: +2, Comunidad: -1'],['Impulsar turismo de naturaleza con límites y educación.','Ambiente: +2, Economía: +1, Comunidad: +2'],['Eliminar toda actividad económica inmediatamente.','Ambiente: +2, Economía: -2, Comunidad: -1']],score:[0,2,1]},
   {q:'Un río sostiene cultivos y abastece poblaciones, pero presenta contaminación. ¿Qué priorizarías?',opts:[['Coordinar tratamiento, monitoreo y uso responsable del agua.','Ambiente: +2, Economía: +1, Comunidad: +2'],['Usar más agua para compensar la contaminación.','Ambiente: -2, Economía: 0, Comunidad: -1'],['Ignorar el problema hasta que sea visible.','Ambiente: -2, Economía: -1, Comunidad: -2']],score:[2,0,0]},
   {q:'Una zona rural pierde jóvenes porque faltan oportunidades. ¿Qué respuesta es más integral?',opts:[['Fortalecer educación, conectividad y emprendimientos locales.','Ambiente: +1, Economía: +2, Comunidad: +2'],['Concentrar todas las oportunidades en la ciudad.','Ambiente: 0, Economía: +1, Comunidad: -2'],['Reducir servicios para evitar cambios.','Ambiente: 0, Economía: -1, Comunidad: -2']],score:[2,1,0]},
   {q:'Una carretera nueva mejoraría la conexión con mercados, pero atraviesa un bosque. ¿Qué harías?',opts:[['Construir sin estudios para terminar rápido.','Ambiente: -2, Economía: +2, Comunidad: 0'],['Evaluar impactos, ajustar el trazado y aplicar medidas de manejo.','Ambiente: +2, Economía: +2, Comunidad: +2'],['Cancelar toda conexión futura.','Ambiente: +1, Economía: -2, Comunidad: -1']],score:[0,2,1]}
  ],
  start(root){let i=0,total=0;const render=()=>{const s=this.scenarios[i];root.innerHTML=card(this,`<div class="og-card"><h4>Situación ${i+1} de ${this.scenarios.length}</h4><p>${s.q}</p><div class="og-choice-grid">${s.opts.map((o,n)=>`<button class="og-choice" data-n="${n}"><b>${o[0]}</b><small style="display:block;margin-top:7px;opacity:.6">${o[1]}</small></button>`).join('')}</div><div class="og-meter"><i style="width:${i/this.scenarios.length*100}%"></i></div><div class="og-feedback" id="decisionFeedback"></div></div>`);root.querySelectorAll('.og-choice').forEach(b=>b.onclick=()=>{root.querySelectorAll('.og-choice').forEach(x=>x.disabled=true);const n=+b.dataset.n;total+=s.score[n];b.classList.add(s.score[n]>=2?'good':'bad');const fb=root.querySelector('#decisionFeedback');fb.textContent=s.score[n]>=2?'Buena decisión: busca equilibrar las tres dimensiones.':'Tiene consecuencias importantes. Piensa en el territorio como un sistema conectado.';fb.className='og-feedback '+(s.score[n]>=2?'good':'bad');setTimeout(()=>{i++;if(i<this.scenarios.length)render();else finish(root,'🌎','¡Decisiones completadas!','Puntaje de equilibrio: '+total+'/8. Una buena decisión territorial considera ambiente, economía y bienestar comunitario al mismo tiempo.')},850)})};render()}
 }
};
function shuffle(a){const x=a.slice();for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function card(g,body){return `<div class="og-panel"><div class="og-head"><div><span class="og-kicker">${g.kicker}</span><h3>${g.icon} ${g.title}</h3><p>${g.intro}</p></div></div><div class="og-body">${body}</div></div>`}
function finish(root,icon,title,text){root.innerHTML=`<div class="og-panel"><div class="og-final"><div class="big">${icon}</div><h4>${title}</h4><p>${text}</p><div class="og-actions" style="justify-content:center"><button class="og-btn" id="ogAgain">Jugar otra vez</button><button class="og-btn secondary" id="ogBack">Volver a juegos</button></div></div></div>`;root.querySelector('#ogAgain').onclick=()=>{const id=root.dataset.game;games[id].start(root)};root.querySelector('#ogBack').onclick=()=>{root.remove();document.querySelectorAll('.game-choice').forEach(x=>x.classList.remove('active'))}}
function findId(btn){const raw=(btn.dataset.game||btn.getAttribute('data-game')||'').toLowerCase();if(games[raw])return raw;const t=btn.textContent.toLowerCase();if(t.includes('conecta'))return'conecta';if(t.includes('misterio'))return'misterio';if(t.includes('decisiones'))return'decisiones';return null}
function bind(){const arena=document.querySelector('#gameArena');if(!arena)return;arena.querySelectorAll('.game-choice').forEach(btn=>{const id=findId(btn);if(!id||btn.dataset.ogBound)return;btn.dataset.ogBound='1';btn.dataset.game=id;btn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openGame(arena,btn,id)},true)});}
function openGame(arena,btn,id){document.querySelector(ROOT)?.remove();document.querySelectorAll('.game-choice').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const root=document.createElement('div');root.id=ROOT.slice(1);root.dataset.game=id;arena.appendChild(root);games[id].start(root);root.scrollIntoView({behavior:'smooth',block:'nearest'})}
function boot(){if(!document.getElementById('og-style')){const s=document.createElement('style');s.id='og-style';s.textContent=css;document.head.appendChild(s)}bind();new MutationObserver(bind).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();