(()=>{
'use strict';
if(window.__ANDINA_PRO_FINAL__)return;
window.__ANDINA_PRO_FINAL__=true;
const $=(s,r=document)=>r.querySelector(s);
const bg=['./assets/andina/file_00000000006481f684d9007640452d51.png','./assets/andina/file_000000003a8c81f685c4c3177c598939.png','./assets/andina/file_00000000426881f6a792160bee4b88c6.png','./assets/andina/file_000000004cac81f6b568a4826989c123.png'];
const sources={marca:['Marca País Colombia','https://colombia.co/pais-colombia/geografia-y-medio-ambiente/region-andina-de-colombia'],travel:['Colombia Travel · Región Andina','https://colombia.travel/es/andes-colombianos'],unal:['Universidad Nacional · Museo de Historia Natural','https://historianatural.unal.edu.co/expo1/andina.html'],ambiente:['Ministerio de Ambiente · Páramos','https://www.minambiente.gov.co/direccion-de-bosques-biodiversidad-y-servicios-ecosistemicos/paramos/']};
function card(cls,title,text,facts,image,source){return `<article class="pro-card ${cls}" style="--pro-bg:url('${image}')"><div class="pro-card-shade"></div><div class="pro-card-content"><span class="pro-kicker">${source}</span><h3>${title}</h3><p>${text}</p><div class="pro-facts">${facts.map(x=>`<span>${x}</span>`).join('')}</div></div></article>`}
function build(){
 const main=$('main'),games=$('#juegos');if(!main||!games)return;
 [...main.querySelectorAll('section')].forEach(s=>{if(s!==games)s.remove()});
 const nav=$('#navLinks');if(nav)nav.innerHTML='<a href="#inicio">Inicio</a><a href="#panorama">Panorama</a><a href="#naturaleza">Naturaleza</a><a href="#vida">Vida y economía</a><a href="#cultura">Cultura</a><a href="#conservacion">Conservación</a><a href="#juegos">Explorar</a><a href="#fuentes">Fuentes</a>';
 const hero=document.createElement('section');hero.id='inicio';hero.className='pro-hero';hero.innerHTML=`<div class="pro-hero-bg"></div><div class="pro-hero-content"><span class="pro-kicker">COLOMBIA · REGIÓN ANDINA</span><h1>Montañas que<br><em>conectan historias.</em></h1><p>Una mirada a un territorio donde cordilleras, agua, ciudades, producción, cultura y biodiversidad forman una misma historia.</p><div class="pro-actions"><a class="pro-btn" href="#panorama">Explorar la región ↓</a><a class="pro-btn ghost" href="#juegos">Entrar a las actividades</a></div></div><div class="pro-hero-note"><b>3</b><span>cordilleras<br>Occidental · Central · Oriental</span></div>`;main.prepend(hero);
 const panorama=document.createElement('section');panorama.id='panorama';panorama.className='pro-section';panorama.innerHTML=`<div class="pro-heading"><span class="pro-kicker">01 · PANORAMA</span><h2>Un territorio de grandes contrastes</h2><p>La Región Andina se ubica en el centro de Colombia. Las tres cordilleras atraviesan el país de norte a sur y generan una enorme variedad de paisajes, alturas, climas y ecosistemas.</p></div><div class="pro-stat-grid"><div><strong>≈25%</strong><span>del territorio nacional, según la referencia del Museo de Historia Natural de la Universidad Nacional.</span></div><div><strong>100 → 5.400+</strong><span>metros de altitud registrados en la región por esa misma fuente.</span></div><div><strong>Magdalena + Cauca</strong><span>dos grandes ríos vinculados al sistema de valles andinos.</span></div></div><div class="pro-map-card"><div class="pro-map-copy"><span class="pro-kicker">EL RELIEVE</span><h3>Occidental, Central y Oriental</h3><p>Entre las cordilleras aparecen valles, cañones, mesetas y altiplanos. Esa variedad ayuda a explicar por qué cambian el clima, la vegetación, los asentamientos y las actividades económicas.</p></div><div class="pro-mountain-art"><span>OCCIDENTAL</span><i></i><b></b><em></em><strong>CENTRAL</strong><small>ORIENTAL</small></div></div>`;main.insertBefore(panorama,games);
 const naturaleza=document.createElement('section');naturaleza.id='naturaleza';naturaleza.className='pro-section';naturaleza.innerHTML=`<div class="pro-heading"><span class="pro-kicker">02 · NATURALEZA Y AGUA</span><h2>La montaña también es una reserva de vida</h2><p>La variedad de alturas permite encontrar bosques secos, bosques andinos y de niebla, bosques altoandinos, humedales y páramos. En este mosaico viven especies adaptadas a condiciones muy diferentes.</p></div><div class="pro-card-grid">${card('wide','Páramos: ecosistemas estratégicos','El Ministerio de Ambiente destaca su papel en la regulación del ciclo hidrológico. Son territorios de gran riqueza biótica y sociocultural y, al mismo tiempo, vulnerables frente al cambio climático',['Agua para consumo y actividades económicas','Frailejonales, humedales y lagunas','Conservación y manejo sostenible'],bg[2],'Ministerio de Ambiente')}${card('','Biodiversidad andina','La Universidad Nacional identifica numerosos ecosistemas y señala que los Andes son un foco importante de endemismos. Entre su fauna destacan especies como el cóndor de los Andes, el oso de anteojos y el tapir de páramo.',['Bosques y humedales','Páramos y alta montaña','Fauna especializada'],bg[1],'Universidad Nacional')}${card('','Paisajes protegidos','Los Nevados, El Cocuy y otros espacios protegidos muestran la variedad de ambientes de montaña y el valor de conservarlos.',['Bosques altoandinos','Páramos','Alta montaña'],bg[3],'Parques Nacionales')}${card('','Agua que conecta','Los valles y cuencas enlazan ecosistemas, poblaciones y actividades. Cuidar la parte alta de una cuenca tiene efectos más allá del lugar donde nace el agua.',['Cuencas','Ríos','Comunidades'],bg[0],'Fuentes institucionales')}</div>`;main.insertBefore(naturaleza,games);
 const vida=document.createElement('section');vida.id='vida';vida.className='pro-section pro-section-dark';vida.innerHTML=`<div class="pro-heading"><span class="pro-kicker">03 · VIDA Y ECONOMÍA</span><h2>Ciudades, campo y producción</h2><p>La región combina grandes ciudades, pueblos y zonas rurales. Esa diversidad se refleja en la producción agrícola, el comercio, los servicios, el transporte y el turismo.</p></div><div class="pro-life-grid"><article><span class="pro-icon">🏙️</span><h3>Una red urbana</h3><p>Bogotá, Medellín, Cali, Bucaramanga, Cúcuta, Manizales, Neiva e Ibagué aparecen entre las ciudades destacadas de la región. Sus actividades conectan educación, empleo, comercio, cultura y servicios.</p></article><article><span class="pro-icon">☕</span><h3>Del campo a los mercados</h3><p>La agricultura y la producción cafetera forman parte de la identidad económica de varias zonas. También tienen presencia la ganadería, la minería y otras actividades productivas.</p></article><article><span class="pro-icon">🚆</span><h3>Servicios y turismo</h3><p>Transporte, comercio, educación, salud, tecnología y turismo conectan territorios y permiten que productos, personas e ideas circulen entre municipios y ciudades.</p></article></div><div class="pro-highlight"><div><span class="pro-kicker">UNA IDEA CLAVE</span><h3>El territorio condiciona, pero las personas también lo transforman.</h3></div><p>Por eso estudiar la Región Andina no consiste solo en localizar montañas: significa entender cómo naturaleza y sociedad se influyen mutuamente.</p></div>`;main.insertBefore(vida,games);
 const cultura=document.createElement('section');cultura.id='cultura';cultura.className='pro-section';cultura.innerHTML=`<div class="pro-heading"><span class="pro-kicker">04 · CULTURA</span><h2>Sabores, sonidos y memoria</h2><p>Las expresiones culturales cambian entre territorios. La región reúne tradiciones culinarias, músicas, artesanías, celebraciones y formas de vida que conservan conocimientos y memoria.</p></div><div class="pro-culture-grid"><article style="--pro-bg:url('${bg[1]}')"><div><span class="pro-kicker">GASTRONOMÍA</span><h3>Ajiaco, tamales y más</h3><p>Colombia Travel recoge preparaciones como ajiaco, tamales, lechona, envueltos de maíz, bandeja paisa y mazamorra. Ingredientes como papa, maíz, legumbres, quesos y carnes tienen un papel importante.</p></div></article><article style="--pro-bg:url('${bg[0]}')"><div><span class="pro-kicker">MÚSICA</span><h3>Una tradición sonora</h3><p>Entre los estilos asociados a la música andina colombiana aparecen bambuco, torbellino, carranga, guabina, sanjuanero y pasillo. El tiple, la bandola y la guitarra forman parte de sus sonoridades.</p></div></article><article style="--pro-bg:url('${bg[3]}')"><div><span class="pro-kicker">OFICIOS Y FIESTAS</span><h3>Identidad que se comparte</h3><p>Tejidos, madera, cerámica, música, danza y celebraciones expresan historias locales. No existe una sola cultura andina: las identidades cambian según cada comunidad y territorio.</p></div></article></div>`;main.insertBefore(cultura,games);
 const conserv=document.createElement('section');conserv.id='conservacion';conserv.className='pro-section pro-section-dark';conserv.innerHTML=`<div class="pro-heading"><span class="pro-kicker">05 · CONSERVACIÓN</span><h2>El reto: conservar y habitar</h2><p>Los Andes reúnen una gran diversidad, pero también han experimentado una fuerte transformación. Proteger agua, bosques y páramos requiere combinar conservación, conocimiento y decisiones responsables.</p></div><div class="pro-challenge-grid"><article><b>01</b><h3>Proteger el agua</h3><p>Conservar páramos, humedales y cuencas ayuda a mantener servicios ecosistémicos esenciales.</p></article><article><b>02</b><h3>Reducir la transformación</h3><p>La pérdida y fragmentación de ecosistemas afecta hábitats y especies. Restaurar y proteger áreas estratégicas es parte de la respuesta.</p></article><article><b>03</b><h3>Conservar con las comunidades</h3><p>La gestión sostenible debe considerar a las personas que habitan y trabajan en estos territorios.</p></article></div><div class="pro-quote">“Comprender la región permite ver que agua, biodiversidad, economía y cultura no son temas aislados.”</div>`;main.insertBefore(conserv,games);
 games.className='section games pro-games';const gh=games.querySelector('.section-head');if(gh){gh.querySelector('.eyebrow').textContent='06 · EXPERIENCIAS';gh.querySelector('h2').innerHTML='Explora la región <em>jugando.</em>';gh.querySelector('p').textContent='Pon a prueba lo que aprendiste con las actividades interactivas.'}
 const fuentes=document.createElement('section');fuentes.id='fuentes';fuentes.className='pro-section pro-sources';fuentes.innerHTML=`<div class="pro-heading"><span class="pro-kicker">07 · FUENTES</span><h2>Para profundizar</h2><p>Estas fuentes institucionales y académicas respaldan y amplían la información presentada.</p></div><div class="source-list"><a target="_blank" rel="noopener" href="${sources.marca[1]}"><b>${sources.marca[0]}</b><span>Geografía, biodiversidad, ríos, ciudades y actividad económica.</span>↗</a><a target="_blank" rel="noopener" href="${sources.travel[1]}"><b>${sources.travel[0]}</b><span>Ciudades, ecosistemas, gastronomía y destinos.</span>↗</a><a target="_blank" rel="noopener" href="${sources.unal[1]}"><b>${sources.unal[0]}</b><span>Altitudes, ecosistemas, biodiversidad y transformación.</span>↗</a><a target="_blank" rel="noopener" href="${sources.ambiente[1]}"><b>${sources.ambiente[0]}</b><span>Páramos, agua, biodiversidad y conservación.</span>↗</a></div>`;main.appendChild(fuentes);
 document.body.classList.add('pro-ready');
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build,{once:true});else build();
})();