const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const menuToggle=$('.menu-toggle'),nav=$('.nav'),backTop=$('.back-top');
menuToggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open);menuToggle.textContent=open?'✕':'☰'});
$$('.nav a').forEach(a=>a.addEventListener('click',()=>{nav?.classList.remove('open');menuToggle?.setAttribute('aria-expanded','false');menuToggle&&(menuToggle.textContent='☰')}));
window.addEventListener('scroll',()=>backTop?.classList.toggle('show',scrollY>600));backTop?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));

const details={
ubicacion:['UBICACIÓN','La Región Andina','Se extiende por el centro y occidente de Colombia alrededor del sistema de los Andes. Para el trabajo escolar, el mapa final debe señalar departamentos, límites, cordilleras y ciudades principales.','Su relieve conecta tres grandes cordilleras: Occidental, Central y Oriental, además de valles interandinos.'],
relieve:['GEOGRAFÍA FÍSICA','Cordilleras y valles','La región está atravesada por las cordilleras Occidental, Central y Oriental. Entre ellas se encuentran importantes valles interandinos y múltiples formas de relieve.','La montaña influye en vías, asentamientos, agricultura, clima y biodiversidad.'],
clima:['GEOGRAFÍA FÍSICA','Clima y pisos térmicos','La altitud modifica la temperatura y permite distinguir pisos térmicos. Por eso, en pocos kilómetros pueden cambiar paisajes, cultivos y formas de vida.','El grupo puede complementar este panel con una gráfica de altura, temperatura y ejemplos de cultivos.'],
agua:['HIDROGRAFÍA','Ríos y cuencas','El Magdalena, el Cauca y otros sistemas hídricos sostienen ecosistemas, poblaciones y actividades productivas.','Las cuencas necesitan protección porque el agua conecta las zonas rurales, urbanas y naturales.'],
biodiversidad:['BIODIVERSIDAD','Páramos, bosques y especies','La variedad de alturas crea hábitats para una gran diversidad de flora y fauna. Los páramos y bosques andinos son especialmente importantes para el equilibrio ecológico.','Aquí conviene añadir especies concretas investigadas por el grupo y sus fuentes.'],
cultura:['GEOGRAFÍA HUMANA','Atlas cultural','La Región Andina reúne comunidades indígenas, campesinas, afrocolombianas y poblaciones urbanas. Sus tradiciones se expresan en música, gastronomía, fiestas, artesanías y formas de vida.','La cultura cambia entre territorios: no existe una sola manera de ser andino.'],
primario:['ECONOMÍA','Sector primario','Agricultura, ganadería, minería y actividades forestales aprovechan los recursos y condiciones del territorio.','Productos como café, papa, flores, frutas y caña tienen importancia en distintos territorios andinos.'],
secundario:['ECONOMÍA','Sector secundario','La industria transforma materias primas en alimentos, bebidas, textiles, químicos, materiales y otros bienes.','Las ciudades y corredores de transporte favorecen la concentración de actividades industriales.'],
terciario:['ECONOMÍA','Sector terciario','Comercio, educación, salud, finanzas, turismo, transporte y otros servicios conectan personas y territorios.','Las grandes ciudades funcionan como nodos de servicios y distribución.'],
ecosistemas:['DESAFÍOS','Pérdida de ecosistemas','La expansión agropecuaria, la deforestación y otras presiones pueden deteriorar bosques, páramos y hábitats.','Soluciones: conservación, restauración, educación ambiental y producción sostenible.'],
desigualdad:['DESAFÍOS','Desigualdad territorial','El acceso a empleo, infraestructura, conectividad y servicios no es igual en todos los territorios.','Soluciones posibles incluyen inversión pública, educación, conectividad y oportunidades económicas.'],
'agua-desafio':['DESAFÍOS','Presión sobre el agua','El crecimiento urbano, la contaminación y las actividades productivas pueden aumentar la presión sobre las fuentes hídricas.','Soluciones: proteger cuencas, reducir contaminación, ahorrar agua y fortalecer su gestión.']};
const modal=$('#info-modal'),modalTitle=$('#modal-title'),modalKicker=$('#modal-kicker'),modalBody=$('#modal-body');
function openDetail(key){const d=details[key];if(!d)return;modalKicker.textContent=d[0];modalTitle.textContent=d[1];modalBody.innerHTML=`<p>${d[2]}</p><p><strong>💡 Para el proyecto:</strong> ${d[3]}</p>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
$$('.detail-btn').forEach(b=>b.addEventListener('click',()=>openDetail(b.dataset.panel)));
function closeModal(){modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true')}
$('.modal-close')?.addEventListener('click',closeModal);$('.modal-backdrop')?.addEventListener('click',closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});

const reflections=['Imagina una solución concreta para proteger un páramo sin afectar injustamente a las comunidades que viven y trabajan cerca.','Piensa en una forma de mejorar la conectividad de una zona rural andina. ¿Qué cambiaría?','Elige una tradición cultural andina y explica cómo podría mantenerse viva entre las nuevas generaciones.','Propón una acción para reducir la contaminación de una fuente de agua cercana a una ciudad.'];
$('#reflection-btn')?.addEventListener('click',()=>{$('#reflection-result').textContent='🎯 '+reflections[Math.floor(Math.random()*reflections.length)]});

const activityData={quiz:[['¿Qué sistema montañoso caracteriza a la Región Andina?',['Los Andes','La Sierra Nevada de Santa Marta','La Amazonía'],0],['¿Cuál es un ejemplo de piso térmico?',['Nival','Oceánico','Polar'],0],['¿Cuál es una actividad del sector terciario?',['Agricultura','Turismo','Minería'],1]],conceptos:[['¿Qué conecta el relieve con la vida humana?',['Influye en clima, vías y asentamientos','Solo cambia los colores del paisaje'],0],['¿Qué ecosistema es clave para el agua?',['Páramo','Desierto costero'],0]],vf:[['La altitud puede modificar la temperatura.',['Verdadero','Falso'],0],['La Región Andina tiene un único tipo de paisaje.',['Verdadero','Falso'],1],['El turismo pertenece al sector terciario.',['Verdadero','Falso'],0]]};
function startActivity(type){const data=activityData[type];let i=0,score=0;const box=$('#activity-feedback');if(!data)return;function render(){if(i>=data.length){box.innerHTML=`<div class="reflection"><h3>🎉 Actividad terminada</h3><p>Resultado: <b>${score}/${data.length}</b>. ${score===data.length?'¡Excelente!':'Buen intento: vuelve a explorar la página y prueba otra vez.'}</p><button class="pill primary" id="again">Jugar de nuevo</button></div>`;$('#again').onclick=()=>startActivity(type);return}const q=data[i];box.innerHTML=`<div class="reflection"><small>PREGUNTA ${i+1} DE ${data.length}</small><h3>${q[0]}</h3><div class="answer-grid">${q[1].map((a,n)=>`<button class="pill ghost answer" data-n="${n}">${a}</button>`).join('')}</div></div>`;$$('.answer').forEach(btn=>btn.onclick=()=>{if(Number(btn.dataset.n)===q[2])score++;i++;render()})}render();box.scrollIntoView({behavior:'smooth',block:'center'})}
$$('.activity-btn').forEach(b=>b.addEventListener('click',()=>startActivity(b.dataset.activity)));

// Legacy player kept for compatibility with existing markup.
const audio=$('#audio'),playBtn=$('#play-track'),prevBtn=$('#prev-track'),nextBtn=$('#next-track'),progress=$('#progress'),volume=$('#volume'),repeatMode=$('#repeat-mode'),trackTitle=$('#track-title'),trackTime=$('#track-time'),trackList=$('#track-list'),upload=$('#music-upload');
let tracks=[{name:'Paisaje andino · pista 01',src:'music/pista-01.mp3'},{name:'Caminos de montaña · pista 02',src:'music/pista-02.mp3'},{name:'Voces de los Andes · pista 03',src:'music/pista-03.mp3'}],current=0,objectUrls=[];
if(audio&&playBtn&&trackList){function renderTracks(){trackList.innerHTML=tracks.map((t,i)=>`<div class="track ${i===current?'active':''}" data-i="${i}"><b>${i+1}. ${t.name}</b><small>♪</small></div>`).join('');$$('.track').forEach(x=>x.onclick=()=>loadTrack(Number(x.dataset.i),true))}function loadTrack(i,auto=false){if(!tracks[i])return;current=i;audio.src=tracks[i].src;trackTitle.textContent=tracks[i].name;renderTracks();if(auto)audio.play().catch(()=>{})}function next(){if(current<tracks.length-1){loadTrack(current+1,true)}else if(repeatMode.value==='all'){loadTrack(0,true)}else{audio.pause();playBtn.textContent='▶'}}function prev(){loadTrack(current>0?current-1:tracks.length-1,true)}playBtn.onclick=()=>{if(!audio.src){loadTrack(0,false);return}audio.paused?(audio.play(),playBtn.textContent='❚❚'):(audio.pause(),playBtn.textContent='▶')};nextBtn.onclick=next;prevBtn.onclick=prev;volume.oninput=()=>audio.volume=volume.value;audio.volume=volume.value;audio.addEventListener('play',()=>playBtn.textContent='❚❚');audio.addEventListener('pause',()=>playBtn.textContent='▶');audio.addEventListener('ended',()=>{if(repeatMode.value==='one'){audio.currentTime=0;audio.play()}else next()});audio.addEventListener('timeupdate',()=>{if(audio.duration){progress.value=(audio.currentTime/audio.duration)*100;const m=Math.floor(audio.currentTime/60),s=Math.floor(audio.currentTime%60);trackTime.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}});progress.oninput=()=>{if(audio.duration)audio.currentTime=(progress.value/100)*audio.duration};upload&&(upload.onchange=e=>{[...e.target.files].forEach(file=>{const url=URL.createObjectURL(file);objectUrls.push(url);tracks.push({name:file.name,src:url})});renderTracks();upload.value=''});renderTracks()}

// New music + personalization layer.
const s=document.createElement('script');s.src='site-enhancements.js';s.defer=true;document.head.appendChild(s);
