(()=>{
'use strict';
const ROOT='./assets/andina/';
const PARAMO='https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/WLE2026_CO_-_P%C3%A1ramo_de_Guerrero_bajo_nubes_%2895%29.jpg/1280px-WLE2026_CO_-_P%C3%A1ramo_de_Guerrero_bajo_nubes_%2895%29.jpg';
const PARAMO_SRC='https://commons.wikimedia.org/wiki/File:WLE2026_CO_-_P%C3%A1ramo_de_Guerrero_bajo_nubes_(95).jpg';
const CITIES={
'Bogotá D.C.':['Panorama bogotá.jpg','HaHa Calabacita','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Panorama_bogotá.jpg'],
'Medellín':['Medellín Panorámica.jpg','Carlos Andres Granada','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Medell%C3%ADn_Panor%C3%A1mica.jpg'],
'Cali':['Panoramic Cali Col.jpg','Aleko','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Panoramic_Cali_Col.jpg'],
'Bucaramanga':['PanoramaBucaramanga.jpg','padasama27','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:PanoramaBucaramanga.jpg'],
'Cúcuta':['Cúcuta Panorámica.jpg','D1090','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Cúcuta_Panorámica.jpg'],
'Manizales':['Manizales-panorama.jpg','Julian Choquette','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Manizales-panorama.jpg'],
'Pereira':['Pereira Vista panorámica.JPG','Alfredo Bianco Geymet','Dominio público','https://commons.wikimedia.org/wiki/File:Pereira_Vista_panorámica.JPG'],
'Armenia':['Armenia Quindío, Colombia. - panoramio.jpg','Jimmy Gómez N','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Armenia_Quindío,_Colombia._-_panoramio.jpg'],
'Ibagué':['Panorama Ibague.JPG','Duvanlopupa','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Panorama_Ibague.JPG'],
'Neiva':['Neiva panoramica.jpg','Martovar69','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Neiva_panoramica.jpg'],
'Popayán':['Popayan - panoramio.jpg','Yender Sanchez','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Popayan_-_panoramio.jpg'],
'Tunja':['Panorámica Centro Tunja.JPG','Petruss','Dominio público','https://commons.wikimedia.org/wiki/File:Panorámica_Centro_Tunja.JPG'],
'Pasto':['Panoramica de Pasto - panoramio.jpg','Carlos A. Revelo Ris…','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Panoramica_de_Pasto_-_panoramio.jpg']
};
const css=`
/* Refuerzo visual v2: estos estilos son autónomos para que el cambio sea visible aunque fallen mejoras anteriores. */
.andina-v2-hero-photo{position:absolute;inset:8% 0 0;border-radius:28px;overflow:hidden;z-index:1;background:#17352b}
.andina-v2-hero-photo img{width:100%;height:100%;display:block;object-fit:cover;object-position:center 55%;filter:saturate(1.04) contrast(1.03)}
.andina-v2-hero-photo:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,#071c1460 0%,#071c1430 42%,#071712d9 100%)}
.hero-art .mountain{display:none!important}.hero-art .sun{z-index:3}
.andina-v2-real-relief{max-width:1200px;margin:0 auto 5rem;padding:0 28px}.andina-v2-real-relief .v2-head{display:flex;justify-content:space-between;gap:28px;align-items:end;margin-bottom:20px}.andina-v2-real-relief h2{font-size:clamp(2rem,4vw,3.2rem);margin:.2rem 0}.andina-v2-real-relief .v2-head p{max-width:500px;opacity:.76}.v2-photo{border-radius:26px;overflow:hidden;background:#10271f;box-shadow:0 18px 50px #0002}.v2-photo img{display:block;width:100%;height:430px;object-fit:cover}.v2-caption{padding:12px 18px;color:#fff;background:#10271f;font-size:.76rem}.v2-caption a{color:#e8c77d}.v2-city-photo{display:block;width:100%;height:120px;object-fit:cover;border-radius:14px;margin:-2px 0 12px}.andina-v2-typical{background:linear-gradient(180deg,#f4efe5,#e8eee8)}.v2-typical-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.v2-typical-card{background:#fff;border-radius:20px;overflow:hidden;box-shadow:0 10px 30px #00000012}.v2-typical-card img{display:block;width:100%;height:155px;object-fit:contain;background:#edf1ea;padding:8px}.v2-typical-card div{padding:12px 14px}.v2-typical-card b{display:block}.v2-typical-card small{display:block;margin-top:5px;opacity:.62;font-size:.66rem}.andina-v2-float{position:absolute;z-index:8;pointer-events:none;animation:v2float 6s ease-in-out infinite;filter:drop-shadow(0 9px 12px #0002)}.andina-v2-float img{width:100%;height:100%;object-fit:contain}.v2-float-cafe{width:110px;height:110px;right:1%;bottom:-25px}.v2-float-beans{width:75px;height:75px;left:-8px;top:26%;animation-delay:-2s}.v2-float-bird{width:88px;height:88px;right:1%;top:18%;animation-delay:-4s}@keyframes v2float{0%,100%{transform:translateY(0) rotate(-2deg)}50%{transform:translateY(-9px) rotate(2deg)}}
@media(max-width:760px){.andina-v2-real-relief{padding:0 16px;margin-bottom:3rem}.andina-v2-real-relief .v2-head{display:block}.v2-photo img{height:280px}.v2-typical-grid{grid-template-columns:1fr 1fr}.v2-typical-card img{height:105px}.andina-v2-float{opacity:.72}.v2-float-beans,.v2-float-bird{display:none}.v2-float-cafe{width:75px;height:75px}}
`;
function addCSS(){if(document.getElementById('andina-v2-css'))return;const s=document.createElement('style');s.id='andina-v2-css';s.textContent=css;document.head.appendChild(s)}
function hero(){const art=document.querySelector('.hero-art');if(!art||art.querySelector('.andina-v2-hero-photo'))return;if(!art.style.position)art.style.position='relative';const box=document.createElement('div');box.className='andina-v2-hero-photo';box.innerHTML=`<img src="${PARAMO}" alt="Paisaje real del Páramo de Guerrero en la Región Andina"><small style="position:absolute;right:12px;bottom:9px;z-index:2;color:white;text-shadow:0 1px 4px #000;font-size:.58rem">Foto: Jedidiahhorne · Wikimedia Commons · CC BY-SA 4.0 · <a href="${PARAMO_SRC}" target="_blank" rel="noopener" style="color:white">fuente</a></small>`;art.insertBefore(box,art.firstChild)}
function relief(){if(document.getElementById('andina-v2-real-relief'))return;const fis=document.getElementById('fisica');if(!fis)return;const s=document.createElement('section');s.id='andina-v2-real-relief';s.className='section';s.innerHTML=`<div class="v2-head"><div><span class="eyebrow">RELIEVE · FOTOGRAFÍA REAL</span><h2>Montañas de la Andina, <em>sin dibujos.</em></h2></div><p>El paisaje real permite reconocer mejor la escala, la vegetación y las formas de la montaña.</p></div><figure class="v2-photo"><img src="${PARAMO}" alt="Paisaje real de montaña andina"><figcaption class="v2-caption">Páramo de Guerrero · Foto: Jedidiahhorne · Wikimedia Commons · CC BY-SA 4.0 · <a href="${PARAMO_SRC}" target="_blank" rel="noopener">ver fuente y licencia</a></figcaption></figure>`;fis.parentNode.insertBefore(s,fis.nextSibling)}
function cities(){document.querySelectorAll('.territory-complete .andina-expand-card').forEach(card=>{const title=(card.querySelector('.aec-title')?.textContent||'').trim();const d=CITIES[title];if(!d||card.querySelector('.andina-v2-city-photo'))return;const img=document.createElement('img');img.className='andina-v2-city-photo';img.loading='lazy';img.decoding='async';img.src='https://commons.wikimedia.org/wiki/Special:Redirect/file/'+encodeURIComponent(d[0]).replace(/%20/g,'_');img.alt='Fotografía de '+title;const cap=document.createElement('small');cap.style.cssText='display:block;margin:-8px 0 12px;font-size:.6rem;opacity:.65';cap.innerHTML=`Foto: ${d[1]} · ${d[2]} · <a href="${d[3]}" target="_blank" rel="noopener">fuente</a>`;card.insertBefore(img,card.firstChild);card.insertBefore(cap,img.nextSibling)})}
function typical(){if(document.getElementById('andina-v2-typical'))return;const e=document.getElementById('economia');if(!e)return;const s=document.createElement('section');s.id='andina-v2-typical';s.className='section andina-v2-typical';s.innerHTML=`<div class="section-head"><div><span class="eyebrow">VIDA COTIDIANA · ASSETS VISUALES</span><h2>Elementos típicos de la <em>Región Andina.</em></h2></div><p>Más imágenes para reconocer productos y símbolos del territorio: café, paisaje cafetero, fauna y montaña.</p></div><div class="v2-typical-grid"><article class="v2-typical-card"><img src="${ROOT}coffee_plant.png" alt="Mata de café"><div><b>☕ Mata de café</b><small>Elaboración propia creada por IA</small></div></article><article class="v2-typical-card"><img src="${ROOT}coffee_beans.png" alt="Granos de café"><div><b>🫘 Granos de café</b><small>Elaboración propia creada por IA</small></div></article><article class="v2-typical-card"><img src="${ROOT}coffee_sack.png" alt="Saco de café"><div><b>🧺 Saco de café</b><small>Elaboración propia creada por IA</small></div></article><article class="v2-typical-card"><img src="${ROOT}blue_bird.png" alt="Ave andina"><div><b>🐦 Ave andina</b><small>Elaboración propia creada por IA</small></div></article></div>`;e.parentNode.insertBefore(s,e.nextSibling)}
function floating(){const defs=[['inicio','coffee_plant.png','v2-float-cafe'],['economia','coffee_beans.png','v2-float-beans'],['cultura','blue_bird.png','v2-float-bird']];defs.forEach(([id,file,cls])=>{const s=document.getElementById(id);if(!s||s.querySelector('.'+cls))return;s.style.position=s.style.position||'relative';const f=document.createElement('span');f.className='andina-v2-float '+cls;f.innerHTML=`<img src="${ROOT}${file}" alt="" aria-hidden="true">`;s.appendChild(f)})}
function run(){addCSS();hero();relief();cities();typical();floating();setTimeout(cities,800);setTimeout(cities,2200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();new MutationObserver(()=>{cities();floating()}).observe(document.body,{childList:true,subtree:true});
})();